# Generated by Django 3.1.1 on 2020-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('tourist_spots_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attraction'),
        ),
    ]
