# Generated by Django 3.1.1 on 2020-10-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_core', '0004_auto_20201014_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_spots'),
        ),
    ]
