# Generated by Django 3.1.1 on 2020-11-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_auto_20201018_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='observations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
